### ISSUE TITLE
Missing SQLITE database

### ISSUE THREAD

**Issue by theapplegates** [ditadi/web-boilerplate#6]
I get an error after logging in.
I don't code, so I am not sure what is wrong. Other than it saying the SQLITE database is missing. I don't think the instructions mention making one. Sorry I'm confused.

Here is the error.
```
code: 'SQLITE_UNKNOWN',
web:dev:     proto: {
web:dev:       message: 'SQLite error: Error code 1: SQL error or missing database: Some("no such table: users")',
web:dev:       code: 'SQLITE_UNKNOWN'
```

Thanks
Paul

**Comment by theapplegates** [comment]
In the .env file I thought the database url looked strange because it had 
`DATABASE_URL=libsql://dog-theapplegates.turso.io`

So I made it 
`DATABASE_URL=https://dog-theapplegates.turso.io`

but it did not work.

**Comment by ditadi** [comment]
@theapplegates Hey, you need to create the tables on your database.

I updated the Readme with the section Migrations. You can check the instructions to create and run the migrations.

**Comment by theapplegates** [comment]
My. Bad. Thanks for the help.
